name: Python application

env:
  sfacg_data: ${{ secrets.SFACG_DATA }}
  cookie: ${{ secrets.COOKIE }}
  auth_data: ${{ secrets.AUTH_DATA }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 准备python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: 签到
      run: python test.py
